### PR TITLE
Adds list_directory_contents public method to GithubClient

### PR DESCRIPTION
**Pull request by eefahy**
Everything's pretty clean here except I wonder if the method name is misleading as it will list both file names as well as directory names. Would love thoughts on that distinction and how we could potentially handle the output of this method. Additionally, this code will return an empty string if it makes a query to a non existent path. We could, perhaps, be more explicit about the failed path.

### CODE REVIEW

**Comment by tallenaz** [comment]
As far as the name, how about just`list_at_path`? It sounds like it behaves like `ls`

**Comment by eefahy** [comment]
it does behave like an `ls` so how about `list_directory_contents` ?

**Comment by tallenaz** [comment]
`list_directory_contents` sounds good to me.

**Comment by eefahy** [comment]
updated and force pushed

**Pull request merged**
